version: "3.8"

services:
  fastapi_server:
    container_name: fastapi_server
    build: ./fastapi_app
    restart: always
    command: "sh -c 'gunicorn -w 3 -k uvicorn.workers.UvicornWorker app.main:app  --bind 0.0.0.0:8000 --preload --log-level=debug --timeout 120'"
    expose:
      - 8000
    ports:
      - 8000:8000

  streamlit_frontend:
    container_name: streamlit_frontend
    build: ./frontend
    restart: always
    command: "streamlit run main.py --server.port=8501 --server.address=0.0.0.0"
    volumes:
      - ./frontend/app:/code
    expose:
      - 8501
    ports:
      - 8501:8501